spring:
  config:
    import: classpath:project.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=organizer
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true # только для отладки
        format_sql: true # только для отладки
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    locations: "classpath:db.migrations"
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    driverClassName: org.postgresql.Driver
    defaultSchema: organizer

logging:
  level:
    by:
      itstep:
        organizaer: INFO # для отладки DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html